### ISSUE TITLE
https://nixos.org/nixpkgs/ page nowhere states the repository

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixos-homepage#12]
I think https://nixos.org/nixpkgs/ at least should state where the repository is?

**Comment by davidak** [comment]
i think @lethalman means the github repo.
if someone is interested in developing packages he has to go to "help" and unter "Developer information" is the "Nixpkgs manual" link. (maybe it has changed since you wrote that)

maybe a short sentence on the frontpage like "development takes place on github" with a link?

**Comment by garbas** [comment]
This information is present on few pages:
 - https://nixos.org/nixos/community.html
 - https://nixos.org/nixos/security.html
 - https://nixos.org/nixpkgs/download.html

I can agree, that inviting or just explaining how to contribute can / should / must be much nicer. but that I hope to do soon.
