### ISSUE TITLE
NixOS Options evaluates literalExample

### ISSUE THREAD

**Issue by krav** [NixOS/nixos-homepage#255]
A `literalExample` given as a set instead of a string displays as `[object Object]`. See `networking.vlans` and screenshot.

![](https://i.imgur.com/9t9dYnT.png)

**Comment by zarelit** [comment]
It looks like nothing is evaluated but the `literalExamples` are shown "as-is" which means that toString is called on the example value directly. Attrsets are represented as JS objects so the result is an unhelpful `[object Object]`. I think that the options page does the right thing because `literalExamples` should be strings, since other tools might have to render them (i.e. `nixos-options`)
