### ISSUE TITLE
ideas for packages page from Arch

### ISSUE THREAD

**Issue by tycho01** [NixOS/nixos-homepage#257]
I was checking the [Arch packages](https://aur.archlinux.org/packages/) page, and noticed it had some features that may be nice for the NixOS package page as well.

listing page:
- visual cues showing when a package version is outdated
- popularity indicator
- filters (they offer an outdated flag, we could do e.g. license, platforms, not broken)

detail page:
- dependency list
- comment section

**Comment by samueldr** [comment]
That's the AUR, not the Arch Linux packages page. (Not that it invalidates the ideas.)

The [actual packages page](https://www.archlinux.org/packages/) also has filters and outdatedness indicators. It does not have a popularity indicator. It also lacks comments.

Follows are thoughts about implementation compared to the current state of the packages listing. I do not consider whether they are desired or not here. This also is mainly a brain dump, don't read too much into that.

* * *

A quick reminder. The packages listing here is entirely driven client-side. At load, all the packages data is fetched and loaded, any filtering is currently done in JS, without any server interaction. It is all entierly static data.

#### Filters

This is trivial, let's not dwell on those. As long as the data is available, it's possible. Just as an example [my alternative packages browser](https://nix.samueldr.com/explorer/?channel=nixos-18.09), which uses the same dataset, has `unfree` filtering. It should be rather trivial to filter out with the other fields.

#### Popularity and comments

Lumped together as they are AUR concepts. Here, popularity is a vote, a tangible thing just like comments. There is no automation with installation or anything fancy.

This would need some read/write backend to save the tangible data.

Additionally, there is something to consider: AUR package names are managed by their backend. When you add a package to the AUR, you register "foo-package", and this name is the canonical way to refer to it. With Nixpkgs, the "identity" of a package comes either from an attribute, or their name, it becomes a bit harder to link the proper popularity and comments. It has happened that attribute names change. Names will change during the lifetime of a package (since they include versions). When attribute names change aliases are (should be) made to ensure no breakage for end-users. The fact that a package's identity can change has to be considered.

#### Outdatedness

In both the AUR and the Arch Linux packages listing, packages can be marked as outdated as a tangible thing on a package. Keeping in mind the considerations from the last section, it could be possible, but there would be no automation; only end-users marking packages outdated.

With that said, it might not work for NixOS and Nixpkgs. The nixos.org packages listing lists packages for current-stable, which will undoubtedly accrue outdated packages, as upstream packages and update in an incompatible-to-backport manner.

#### Dependency list

This could be neat, though considering all the data that's currently being loaded at once for the packages listing, it can't happen with the way the packages listing is handled. Compression may make this a minimal increase in size, but it will incur a fee in performance at load time as the JSON decoding still has to happen for the whole file, and then there's a bit of processing.

Without having discrete per-package information that could be loaded asynchronously, I think it technically is infeasible. Though, having discrete information that way *could* be possible, even with the way the website is statically generated.

**Comment by tycho01** [comment]
Thanks for your comments.
On the dependency list, I imagine the reason it works for them is it's not loaded in for all packages at once due to their separate views.

**Comment by samueldr** [comment]
>  On the dependency list, I imagine the reason it works for them is it's not loaded in for all packages at once due to their separate views.

Pretty much, one actual page per package. In fact, nowhere do they preload all the package set like nixos.org does. Though this means that there is a dynamic back-end used to generate the pages, while the nixos.org website is entirely static.

**Comment by garbas** [comment]
I believe the some ideas were already implemented and some does not makes sense. please reopen if i missed something.

**Comment by tycho01** [comment]
@garbas hm, going over the original post here again, I'm under the impression none of those have currently made it into the [listing](https://nixos.org/nixos/packages.html?channel=nixos-19.09&query=haskell) or [detail](https://nixos.org/nixos/packages.html?attr=haskellPackages.zxcvbn-c&channel=nixos-19.09) pages?
