### ISSUE TITLE
Content from old Community page

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#402]
The PR https://github.com/NixOS/nixos-homepage/pull/398 removed several content from the community page that don't fit there. We have to find a new place.

Content (my suggestion where to put it)

- ~Contributing to NixOS (Contribution Guide)~ (https://github.com/NixOS/nixos-homepage/pull/411)
- ~Bugs (Help page and GitHub Readme)~ (https://github.com/NixOS/nixos-homepage/pull/411)
- ~Documentation (Documentation page)~ (https://github.com/NixOS/nixos-homepage/pull/411)
- ~Source repositories (Contribution Guide)~ (https://github.com/NixOS/nixos-homepage/pull/411)
- ~Commercial support (own page, linked in footer)~ (https://github.com/NixOS/nixos-homepage/pull/412)
- ~Donations (Donation page)~ (https://github.com/NixOS/nixos-homepage/pull/399)
- ~Acknowledgments (Donation page)~ (https://github.com/NixOS/nixos-homepage/pull/399)

Archive: https://web.archive.org/web/20200415173119/https://nixos.org/nixos/community.html

The actual content:

```
<h3>Contributing to NixOS</h3>
<div class="row-fluid">
  <div class="span8">
    <p>It’s pretty easy to modify NixOS. All you need to do is get a copy
    of the Nixpkgs repository (which contains the NixOS sources as
    well):</p>

<pre>
<span class="nix-command">git clone git://github.com/NixOS/nixpkgs.git</span>
</pre>

    <p>After making modifications to the sources, you can use them as
    follows:</p>

<pre>
<span class="nix-command">nixos-rebuild switch -I nixpkgs=/path/to/my/nixpkgs</span>
</pre>

<p>If you think your changes are useful to the rest of humanity, then
please open a <a
href="https://github.com/NixOS/nixpkgs/pulls"><strong>pull request on
GitHub</strong></a>, or <strong>send a patch</strong> to the <a
href="[%root%]learn.html#discourse"><tt>Discourse</tt> forum</a>. If you
want to contribute regularly, you may want to ask for commit access to
our GitHub repositories (please ask <a
href="https://nixos.org/~eelco/">Eelco</a>, or on the <tt>#nixos</tt>
IRC channel).</p>  </div> <div class="span4"> <script
type="text/javascript"
src="https://www.openhub.net/p/25550/widgets/project_basic_stats.js"></script>
</div> </div>

<h3><a href="https://github.com/NixOS/nixpkgs/issues">Bugs</a></h3>
<p>If
    you think you’ve found a bug, please report it in the <a
    href="https://github.com/NixOS/nixpkgs/issues"><strong>Nixpkgs
    issue tracker</strong></a> (please use the label <strong>6.topic:
    nixos</strong>).
</p>

<h3>Documentation</h3>

<ul>

  <li>The <a href="[%nixosManual%]">NixOS manual</a> has a <a
  href="[%nixosManual%]#ch-development">whole chapter on NixOS
  hacking</a>. Also, check out the sections on <a
  href="[%nixosManual%]#sec-configuration-syntax">the syntax of NixOS
  modules</a> and on <a href="[%nixosManual%]#sec-custom-packages">how
  to add your own packages</a>.</li>

  <li>The <a href="[%nixpkgsManual%]">Nixpkgs manual</a> has a lot of
  information on how to add packages to Nixpkgs.  In particular, you
  should check out the <a
  href="[%nixpkgsManual%]#chap-quick-start">“Quick Start” chapter</a>
  for an overview of the process of adding a package.</li>

  <li>The Nix manual has <a
  href="[%nixManual%]#chap-writing-nix-expressions">a chapter on
  writing Nix expressions</a>, including the syntax and semantic of
  the Nix expression language.</li>

  <li>There is a <a
  href="https://nixos.org/~eelco/pubs/nixos-jfp-submitted.pdf">paper
  on NixOS</a> has a lot of information on the NixOS module
  system (especially section 6).</li>

</ul>

<h3>Source repositories</h3>

<p>The sources of all Nix-related projects are in the <a
href="https://github.com/NixOS/">NixOS organization on
GitHub</a>. NixOS lives in the <a
href="https://github.com/NixOS/nixpkgs/tree/master/nixos">nixos</a>
subdirectory of the Nixpkgs repository.</p>

<h3>Discourse</h3>

<p><a href="https://discourse.nixos.org">discourse.nixos.org</a> hosts
a community of Nix developers and users, providing resources to help
you:</p>

<ul>
<li>find answers to your Nix/Nixpkgs/NixOS/NixOps questions</li>
<li>discuss current and future directions of the project</li>
<li>evangelise and promote Nix in your community</li>
</ul>

<h3>IRC channel</h3>

<p>The NixOS developers hang out on the <a
href="irc://irc.freenode.net/#nixos"><tt>#nixos</tt> channel</a> on <a
href="https://freenode.net/"><tt>irc.freenode.net</tt></a>.  This
channel is <a href="https://logs.nix.samueldr.com/nixos/">logged</a>.</p>

<h3>Blogs</h3>

<p><a href="https://planet.nixos.org/">Planet</a> aggregates blog posts written
by the community and <a href="https://www.reddit.com/r/NixOS/">/r/NixOS</a>
also contains useful resources.</p>

<p>To add yourself to <a href="https://planet.nixos.org/">Planet NixOS</a>,
fork the <a
href="https://github.com/NixOS/nixos-org-configurations">nixos-org-configurations</a>
repo and add the feed source to <a
href="https://github.com/NixOS/nixos-org-configurations/blob/master/nixos-org/planet-feeds.nix">planet-feeds.nix</a>
then make a pull request.</p>

<h3>Meetups</h3>

<p>Europe:</p>
<ul>
<li><a href="http://www.meetup.com/Amsterdam-Nix-Meetup/">Amsterdam Nix Meetup</a></li>
<li><a href="http://www.meetup.com/Berlin-NixOS-Meetup/">Berlin NixOS Meetup</a></li>
<li><a href="https://www.meetup.com/Greater-Copenhagen-NixOS-User-Group">Greater Copenhagen NixOS User Group</a></li>
<li><a href="https://www.meetup.com/NixOS-London/">London NixOS Meetup</a></li>
<li><a href="http://www.meetup.com/Munich-NixOS-Meetup/">Munich NixOS Meetup</a></li>
<li><a href="https://blog.shackspace.de/?p=5829">Stuttgart NixOS Meetup</a></li>
</ul>

<p>America:</p>
<ul>
<li><a href="http://www.meetup.com/Bay-Area-Nix-NixOS-User-Group/">Bay Area Nix/NixOS User Group</a></li>
<li><a href="https://www.meetup.com/New-York-Nix-Users-Group/">New York Nix Users Group</a></li>
</ul>

<p>Asia:</p>
<ul>
<li><a href="http://www.meetup.com/Tokyo-NixOS-Meetup/">Tokyo NixOS Meetup</a></li>
</ul>

<h3>Continuous builds</h3>

<p><a href="https://github.com/NixOS/hydra">Hydra</a> continuously builds NixOS:</p>

<ul>
  <li><a href="https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents">Status
  of the <tt>master</tt> branch</a>, used to update the <a
  href="https://nixos.org/channels/nixos-unstable/"><tt>nixos-unstable</tt>
  channel</a>.</li>
  <li><a href="https://hydra.nixos.org/job/nixos/release-[%latestNixOSSeries%]/tested#tabs-constituents">Status
  of the <tt>release-[%latestNixOSSeries%]</tt> branch</a>, used to update the <a
  href="https://nixos.org/channels/nixos-[%latestNixOSSeries%]"><tt>nixos-[%latestNixOSSeries%]</tt>
  channel</a>.</li>
</ul>

<h3>Commercial support</h3>
<!-- Please submit a PR to add your company -->
<p>For professional support, a number of consulting companies are
available (sorted in alphabetical order):</p>
<ul>
  <li><a href="https://www.enlambda.com/">Enlambda</a></li>
  <li><a href="https://nixos.mayflower.consulting">Mayflower</a></li>
  <li><a href="https://nixcloud.io/">nixcloud</a></li>
  <li><a href="https://www.numtide.com/">NumTide Ltd</a></li>
  <li><a href="https://obsidian.systems">Obsidian Systems</a></li>
  <li><a href="https://serokell.io/">Serokell</a></li>
</ul>
```

**Comment by rkoe** [comment]
Is there any plan to fix this soon? It seems the webpage more and more degrades and loses more and more information. :(
Now, "thanks" to the too-early-merged #398, there's now *no link* to the bugtracker anymore on the homepage! And also no link to the github-repository (except a more or less "hidden" github-icon on the top-right of the Nixpkgs-section, which noone will find)!

**Comment by garbas** [comment]
Hi @rkoe,

please help me understand your position and the context you are coming from. I really want to understand - not pretending in any way - why you think this is important or more important to block other work. I don't consider myself to know everything. I remind myself everyday that we are here (contributing to NixOS project), because we want it to succeed, and that is also why we sometimes *argue* with each other :smiley: 

Since I'm asking you to share your position I think is only fair to you to share mine. I agree with you that webpage should  have information where to report bugs and where to contribute. I think we can even agree that this information should not be at prominent location (landing page or header) but should probably be somewhere in the footer and also a longer Contribution guide. Both footer and Contribution page are being worked on and you can expect this information to be back in a week or two.

Regarding "proper order" of how changes are done to the website. Personally I find it more important to transform the website then to be perfect in the process, even if that means breaking the website from time to time. I think we finally have some energy behind the effort to change the website, which is in a need of a refresh for a long time. We - the marketing team - are far from where we want to be with the website, but we are determined to take a step closer each week, and by the end of the year 2020 we will not even remember this hiccups along the way. What is important, and is going to be hard, is to keep the same energy for the whole year. Please help us with that, any nice word counts :smile:

**Comment by rkoe** [comment]
Hi @garbas,

thanks for explaining your position.

My position is:
- The information should be findable on the homepage. That's where users expect this information. Yesterday, I've found a bug, and I searched for the bugtracker-link on the homepage, but could not find one. I even could not find *any* link to the nixpkgs-github-repository.
  Since I know Nix/NixOS for quite some time now, I can work around this. But (a) this is frustrating and (b) others won't be able to work around, and so would not be able to find the bugtracker at all, and so may give up and/or think that Nix/NixOS does not have a bugtracker or does not want to receive bug reports.

  There even isn't a findable link to the nixpkgs-repository on the homepage at all (and still not resolved #372 even makes it worse).

- I'm trying to look at things from a users perspective (or even from an unexperienced users perpective). Usability counts.

- Don't break things.
  Unfortunately, I'm more and more are frustrated with NixOS, since things there are breaking constantly, without any good reason. And often, nobody cares about the fix or nobody has time for fixing. And nobody cares if things are working or not, and there's no QA. Examples below [1].
  It feels like the attitude in Nix/NixOS is "Let's break things now, somebody else can fix it later."
  In my opinion, such an attitude/approach is ok for some toy or experiements. But not for a serious productive distribution -- which I think Nix/NixOS should be. But QA seems to be nearly completely missing on Nix/NixOS.

> Regarding "proper order" of how changes are done to the website. Personally I find it more important to transform the website then to be perfect in the process, even if that means breaking the website from time to time.

I **strongly** disagree here. The website is the central place of information for Nix/NixOS. If some user searches information about Nix/NixOS he searches there. So, the information should be findable there. Always. **Breaking it is a no-go.**
The process does not need to be perfect, but the information must be there.
Removing useful/necessary information from the homepage because "it structurally does not really fit where it currently is", without adding it to an other useful place, is a no-go in my opinion.

The ways to solve this would be:
- First, think about a good structure for the website, *before* changing things.
- Then, build the new page and make changes. Ideally build the new page completely (while the old page is still online) and then switch to the new page.
  If this cannot be achieved and incremental updates are thought to be necessary, at least add the information elsewhere (maybe with a non-perfect design), before removing it.

----------

[1] Examples:
- A change to the Qt environment broke may packages. Nobody is interested in fixing them.
  All I got was 'I would have liked to fix them, but I don't have the time'.
  In my opinion, if a change breaks things and these are not fixed *before*, the change must not be done.
  This resulted in a frustrated post on discourse: https://discourse.nixos.org/t/please-fix-all-packages-which-were-broken-by-the-qt-wrapping-changes/6444/
  (I agree that my wording unfortunately wasn't nice, since I was quite frustrated there; but the problem still exists.)
- Links to all Nix expressions on the homepage-package-list are broken quite for a while now. These links were really useful -- now, you have to manually search through the github-tree to find the nix-expressions for a package. Why?
  Nobody knows when it will be fixed; and the bugreport (#372) was closed without a fix.
  And these links broke before, probably several times.
- Broken packages: There are *many* broken packages in NixOS, and many "survive" several releases. Some even fail to compile (e.g. "nixos.blink"), some do not run, some segfault, some are unmaintained for years.
  And there's not even a way to know or document if a package is broken, outdated, unmaintained etc.!
- Update to 20.03 broke serveral things, e.g.:
  - audio did not work anymore (without a note in the release notes)
  - programs using GLX broke (and it's unknown how to fix this)
  - ACME removed all current certificates and was not able to create new ones (since it triggered rate limits), and so it broke the TLS-encryption of webservers.

A working QA could/should have prevented (or at least fixed) all those problems.

What's necessary here, is:
- A change of mind: QA is important, if Nix/NixOS wants to be more than a toy.
- A good QA (as all larger distributions have).
- Some mechanisms to detect/prevent broken/unmaintained/... packages.
- Some people or mechanisms to check changes/commits for their negative effects, and fix those *before* the change is done/merged. (Or at least before the change/merge gets into a release; nothing against an additional 'experimental' channel, where it's totally ok that things constantly break.)

I'm willing to help here, since (a) in my opinion that's the most lacking part of Nix/NixOS (besides the bad user-interface/non-nerd usability), and (b) this could improve the usability of NixOS a lot and reduce frustration. I'm currently working on a concept and will offer it for discussion soon (hopefully).

**Comment by davidak** [comment]
Hey @rkoe, thanks for your perspective. I totally understand your frustration since i often feel it too regarding this project. A lot of things are not perfect and we have limited resources. So i try my best to help as i can. I have created 228 issues for problems i found where half of them are still open. But i also get better and i'm able to fix them myself.

To make progress here, where do you expect a "Report an issue" link from an enduser perspective?

We could create a Contribution guide in 5 minutes that already contains the important links and a disclaimer "We currently work on a new contribution guide." maybe with link to an issue where people can contribute.Then the page would look more broken, but the information is there. Would that be a fast solution for the specific problem you see here @rkoe?

Regarding QA etc. I think most people in the community would like to have more QA, but as said before, we have limited resources. I have done QA for the existing release notes for the last release. And i try to get the components i use in a good state by testing and reporting issues.

I have a bigger vision for NixOS that i want to write down when i have some time. One part could be funding. So concrete question: So concrete question: How much money would you donate per month for NixOS? We can define a goal and when we get enough money, we could pay for example the release managers first, then maybe another part time employee that has a maintainer role and merge PRs etc or one that fixes hard problems that the community don't want to tackle. When people don't need another job to survive and get money for contributing to NixOS, they can invest more time and we can fix more problems. What do you think?

**Comment by rkoe** [comment]
> To make progress here, where do you expect a "Report an issue" link from an enduser perspective?

- In the current structure (About, Download, Learn, Packages, Options, Community, Governance, Donate), I would definitely expect it in "Community".
- Independent from the current structure, I might expect it in "Support" or "Development".
- I would also expect the "Wiki" in "Community" (since it's a "user-maintained wiki" definitely belongs to the community) -- in addition the link in "Learn".
- I would expect the nixpkgs-github-link in "Development" or "Packages", and the generic github-link in "Development". Since there currently is no "Development"-sections, I would go with "Community".
  (But I think a "Development"-section could be nice.)
- I would expect a "Nix Community Cookbook" also under "Community" and not only under "Learn"
- By the way: I stumbled over inconsistent naming and inconsistend order:
  - in "Community", there are "Forum", "Chat", "redit", "stackoverflow" (w/o a direct link)
  - in "Learn", there are "Discourse" and "IRC", "Stackoverflow" (with a link), "Reddit".
- I also cannot find the links to NixOps and Disnix that have been there before.
- By the way: I was also puzzled, that although there is a switcher on the top left between "Site Home", "NixOS", "Nix" and "Nixpkgs", this is not really a switcher -- the top menu changes (-> some menu points are removed -- why is "Packages" hidden when I select Nixpkgs?), when you click on them, the "site switcher" switches back to "NixOS".
  And both "Site Home" and "NixOS" show "NixOS" in the switcher. Very confusing.

I think a completely reworked structure is necessary for the homepage.

> We could create a Contribution guide in 5 minutes that already contains the important links and a disclaimer "We currently work on a new contribution guide." maybe with link to an issue where people can contribute.Then the page would look more broken, but the information is there. Would that be a fast solution for the specific problem you see here @rkoe?

That would probable be a great guide for beginners. But it would not replace direct links on the homepage.

> Regarding QA etc. I think most people in the community would like to have more QA, but as said before, we have limited resources. I have done QA for the existing release notes for the last release. And i try to get the components i use in a good state by testing and reporting issues. I also plan to document package testing, so we can prevent runtime issues.

That's good. But I think we need some QA-structure. E.g. fields in the package-descriptions, which tell if the package is currently maintained, if it has been tested, if it is broken etc.
I'm working on a proposal about this.

> I have a bigger vision for NixOS that i want to write down when i have some time. One part could be funding. So concrete question: So concrete question: How much money would you donate per month for NixOS?

Funding definitely is interesting. But I have not yet thought about how much money I would donate, and I'm not sure about the payment-structure. Most work will always be done by volunteers, but yes, QA could be a paid job.
But I think I myself could help NixOS more by working on it, than by donating money.

**Comment by davidak** [comment]
Thanks for the many hints. We will see what to do about them. Many things are known.

>I think a completely reworked structure is necessary for the homepage.

We are working on that right now. That's why we remove and add pages.

>We could create a Contribution guide in 5 minutes

I made a Contributing guide in 3 hours: https://nixos.org/guides/contributing.html (you find it under Learn)

We will have direct links in the footer.

>That's good. But I think we need some QA-structure. E.g. fields in the package-descriptions, which tell if the package is currently maintained, if it has been tested, if it is broken etc.

there is a maintainer field and a broken flag. i like to establish automated package testing, so we know when packages are broken. but package maintainers have to add tests and fix issues. i still failed to get my PR merged https://github.com/NixOS/nixpkgs/pull/75117 after that i would document it, so other package maintainers can follow

>But I think I myself could help NixOS more by working on it, than by donating money.

yes, that helps more

**Comment by davidak** [comment]
All content is back online.
