### ISSUE TITLE
Make footer stick to bottom

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#430]
this looks bad

![Screenshot from 2020-05-25 17 35 46](https://user-images.githubusercontent.com/91113/82827083-8e78c900-9eae-11ea-9e21-5f9e79236daf.png)

**Comment by samueldr** [comment]
Just saying, a quick cheat for this, in a sane web development world, would be to set `min-height: 90vh` to the main container (so it's pushed down, but still peeks), but using `vh` is a **terrible idea** in a world where iOS Safari exists, as `vh` units cause recalcs of the layout every time you change the scroll direction as the viewport dimensions "physically" change when the navbar is shown or hidden.

Though, as we're "throwing" this away in the medium term, it should be good enough. Anyway it shouldn't actually cause changes in many cases because the often-narrow viewport causes the main container to be taller than its min-height.

Here's food for experiment:

```
.container.main {
    min-height: calc(80vh - 60px);
}
```

**Comment by davidak** [comment]
I think this was fixed in the redesign. I can't find a page with such few contents to test.

@samueldr do you think it's fixed?
