### ISSUE TITLE
Redesign of the website

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-homepage#449]

**Comment by BenSchZA** [comment]
Hey @garbas ! I'm reposting this here from IRC channel, because this seems like the relevant issue for it. A number of links will be broken back to the `/nix` and `/nixos` routes - I know I personally always links back to `/nix` in repos I contribute Nix derivations to.

`Hi everyone! I love the new NixOS website, but it's broken a number of project links back to nixos.org/nix. Would it be possible to redirect nixos.org/nix back to nixos.org or relevant page?`

`^ on a similar note, maybe redirect `https://nixos.org/nixos/packages.html#abc` to `https://nixos.org/nixos/packages.html?query=abc`?`

Thanks!

**Comment by BenSchZA** [comment]
Also happy to look into this.

**Comment by samueldr** [comment]
Just leaving a thought I had about this. "Redesign of the website" is a wrong way to think about that.

What we actually need, I believe, is a brand identity design, which includes the website. (I think that's what you had in mind already.)

The main difference here is that the website redesign is built from the brand identity. And the brand identity can be designed to accommodate more than the website.
