### ISSUE TITLE
homepage styles contaminate manuals

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixos-homepage#489]
Looks like the styling for `#examples` on the homepage leaks to the manual:

https://nixos.org/nix/manual/#examples

**Comment by samueldr** [comment]
I had fears that it would happen when I saw how it was implemented, but didn't want to dwell too long on something we are going to re-implement in the near future.

Using a strategy like [rscss](https://rscss.io/) to "scope" class names would have been the prudent choice.

Something like having a class for the page (either containing the whole main section, or to the body), and then scoping would have helped prevent this.

```html
<section class="page-home">
<div class="landing-jumbotron">
<!-- ... -->
</div>
<div class="home-examples">
<h1>Examples</h1>
<div class="examples">
<!-- ... -->
</div>
</div>
</section>
```

And the selectors would be generally safe to apply.

```css
.home-examples .examples {
  /* You **know** you are not accidentally writing on another component. */
}
```

Another scheme that exists is [BEM](http://getbem.com/), though my preferences are with rscss :).

(These are notes for thoughts for the future implementation. Though they could also be the fix for the current issue.)
