### ISSUE TITLE
Add a public calendar for public things

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixos-homepage#498]
```
21:37 <zimbatm> infinisil: oh right, do you know when that is happening?
21:38 <qyliss> I believe there's a steering committee meeting this week
21:38 <qyliss> well, next week
21:45 <colemickens> we need a calendar on nixos.org
21:47 <qyliss> that would be cool 
```

 * https://logs.nix.samueldr.com/nixos-dev/2020-07-26#1595800020-1595799454;

This would be helpful for transparency about the RFC process, but more to the point, useful for forgetful people in the community!

I wonder, too, what *other* useful things could be in the calendar.

**Comment by worldofpeace** [comment]
Also great for release blocker review meetings, release manager meets, and if we get office hours going again.

**Comment by infinisil** [comment]
There is a [google calendar](https://calendar.google.com/calendar/u/0/embed?src=b9o52fobqjak8oq8lfkhg3t0qg@group.calendar.google.com), it's been used for a while, though it's read-only with only few people being able to write to it.

And there's now also a [discourse community calendar](https://discourse.nixos.org/t/community-calendar/18589), though it doesn't have many features.

But furthermore there are some developments tracked in https://github.com/NixOS/nixos-org-configurations/issues/231 already, which I think is a better place for this, since it's not very directly related to the website.

**Comment by fricklerhandwerk** [comment]
Regardless of whether we get a community-owned software stack any time soon, it would be great to show the two big calendars prominently, so more beginners can drop right into current events. @lassulus suggested that @hsjobeki maybe you can find a place for two links with labels somewhere?
