### ISSUE TITLE
Why don't we switch to a more modern technology?

### ISSUE THREAD

**Issue by hugolgst** [NixOS/nixos-homepage#518]
Hello, 

I think that moving to modern technology like Vue, React could be beneficial for NixOS such as more people could contribute to the website because it is currently these technologies that are the most used ones.
It could also be more maintainable and scalable.

I am up for grabs if you want.
Thanks a lot

**Comment by jonringer** [comment]
There's currently a lot of work being done to revamp the website, it just haven't been made publicly available.

**Comment by hugolgst** [comment]
Is this work available in the Pull requests ?

**Comment by jonringer** [comment]
you can take a look here: https://github.com/NixOS/nixos-homepage/pull/506

**Comment by samueldr** [comment]
As this website is a *static* website, it not take advantage of the benefits of "modern technologies".

As a goal, and I'm pretty sure the whole website maintainers team agrees, we want to continue producing "dumb" HTML pages as the output, with some minor JavaScript enhancement using the good ol' technique called *graceful degradation*.

Now, as to the tooling to generate the website? It might change in the future. It's likely to change in the future. Though this does not change anything about the fact that we are not going to end up making an SPA website. Sure, those "modern technologies" can also produce a static website as an output, but at that point, is it really more objectively maintainable to do so? I don't know for sure.

Maintainability is subjective, and part of that comes down to the *maintainer*'s own experiences.

Recapping: it's not the time for it, and when comes the time, options will be looked at thoroughly.

(Leaving open for other maintainers of the website to comment if they desire to.)

**Comment by hugolgst** [comment]
You're right, it'll take too much time to implement but I think that's much clearer to use one even for a simple static website.
I'd also like to know how I could get involved in the project

**Comment by samueldr** [comment]
I'm sure there are other ways, but here's how I got involved: trying to fix things on the website!

Though you're basically asking on the wrong two-month duration because of how this current version is being re-shaped. Getting a new contributor up-to-speed with the current tooling *in addition* to the new setup and the new plans wouldn't really be feasible until it's all merged in, which is planned to happen in the next few weeks.

At that point it should be easier to understand the new setup, and plans will be made clearer for anyone anyway. So I guess that at the current time it's "sit tight and watch".

Though, if you want to get more familiar with some things, the current tooling for generating pages is [Template Toolkit](http://www.template-toolkit.org/), which in the first phase of the revamp is still being used. Sure, that's all kinds of manners far from modern toolkits, but it's pretty serviceable, and time has proven it works just fine.

The new setup has made almost no changes to the tooling. The main difference being that it uses [LESS](http://lesscss.org/) as a CSS pre-processor, but without the usual assets pipeline. Why no assets pipeline? That's because it'll probably the one in use by whatever tooling we switch to. Not choosing one allowed me to push the decision to later.

**Comment by garbas** [comment]
closing since there is nothing actionable (anymore).
