### ISSUE TITLE
News page wider than viewport

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#543]
![signal-2020-09-21-002213](https://user-images.githubusercontent.com/91113/93723958-599e2980-fba3-11ea-84a5-2709af843705.png)

On Xiaomi Redmi Note 4 with Firefox Klar.

Reproducible on desktop Chromium.

![Screenshot from 2020-09-21 00-44-31](https://user-images.githubusercontent.com/91113/93723997-b0a3fe80-fba3-11ea-882a-2d659bb6da39.png)

**Comment by samueldr** [comment]
This is caused by the table-based layout.

There are elements that *would* normally end up being set to a max-width properly, but inside a table rules are just slightly different due to *legacy reasons*.

The solution here is to change the news rendering in the `xsl` so it doesn't use a table anymore.

**Comment by garbas** [comment]
How news are used on the website is going to be "radically" changed soon, right after the redesign, the work/discussion is being tracked in #446. But @samueldr  :100: for fixing it until then.
