### ISSUE TITLE
Ascinema on mobile 2 (overflow)

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixos-homepage#597]
The videos overflow the screen.

I doubt it's soecial to my device (android one - motorola), is it?

_For some inexplicable readon I'm technically barred from pasting from the mobile._

**Comment by garbas** [comment]
The video should not overflow. I'm attaching the screenshot from my phone

![photo6046177560712295166](https://user-images.githubusercontent.com/20208/95308479-40c39280-088a-11eb-9efd-1b52e03b1426.jpg)

Can you provide a screenshot from your phone? Also which browser are you using?

**Comment by blaggacao** [comment]
![Screenshot_20201007-085938](https://user-images.githubusercontent.com/7548295/95341082-8593fd00-087b-11eb-8fa3-846b3b8f85a7.png)

I agree on the landscape mode, here is how it looks on my phone: slightly off.

**Comment by garbas** [comment]
@blaggacao which browser is that?

**Comment by blaggacao** [comment]
Ok sorry, I didn't figure it might be relevant.

- Motorola Android One
- DuckDuckGo Browser v5.66.1

**Comment by turboMaCk** [comment]
I think this might be caused by right padding on `<li>` element as visible in the screenshot below.

![image](https://user-images.githubusercontent.com/2130305/97312351-adb4c180-1865-11eb-85ec-ed4d9c9c2c79.png)

At least its size looks somewhat similar to the offset I see on screenshots there. In any case I believe this padding should not be there on mobile version as it generally breaks the center alignment of that content.

**Comment by samueldr** [comment]
That padding will not fix the overflow.

The overflow comes from a badly tested rule set for handling vertical/horizontal in [`site-styles/components/asciinema.less`](https://github.com/NixOS/nixos-homepage/blob/ce5d0225b7498dacd7ec1581cd9b75f0491e3f2f/site-styles/components/asciinema.less#L19-L23).

To reproduce:

 * Have an horizontal window, rather than vertical window with `xs` or smaller.

Pro-tip: Docking the inspector at the bottom helps here.

**Comment by turboMaCk** [comment]
I can reproduce it now. It's impossible to reproduce using mobile size simulation but in classic desktop mod with both low height and width and with player open this easily reproducible (both firefox and chrome/brave)
