### ISSUE TITLE
Governance -> Community

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixos-homepage#599]
Semantically governance does govern the community. The current layout suggest governance and community are two separate things.

Incorporate governance into the community tab. I see why it might be currently separated, so that it stands out. But that rather looks like a concession than a semantic fit.

Once that's done, it becomes easier to explain how community and governance relate.

_I actually don't know which way more reflects the actual situation (separate things, vs governance beeing the governance of community), but the canonical interpretation would be the above claimed one, I guess._ 😉

**Comment by davidak** [comment]
the teams govern the project
the community use and develops the project

these are two separate things visitors might want to learn more about

**Comment by blaggacao** [comment]
It says little about the relationship between teams and community.
Do they really proxy through the project?

**Comment by garbas** [comment]
@blaggacao You are more then right! :+1: 

This two items (and donate page) were added because:
- I didn't know how NixOS is governed and organized and needed to figure out this by talking to people. I still don't know all the details and quite some stuff is out in flux, but we will slowly get there.
- There was not enough content for the menu and not enough time to work on some content since priorities are different. You can see that we work in small steps and you can expect this thing to change.

How is going to change? Donate, Community and Governance will eventually merge, how I don't exactly but I'll figure it once we get there. We'll discuss it prior to that at the marketing team meeting. Most likely the "merge page" is going to be called Community. Two new pages are going to be added: News/Blog and Success stories. But that will take some time to compile the content. I expect this to be done until 21.03 release is out.

If you wish to help shape nixos.org please consider joining the marketing team. All details how to join are here: https://discourse.nixos.org/t/accepting-new-members-to-the-marketing-team/9305

**Comment by blaggacao** [comment]
@garbas off topic. I considered joining seriously but I'm unable to do much for the good part of the next 6 month, based on my current engagement. So it would only be "gentle onboarding". Would you still consider it's viable joining now?

**Comment by garbas** [comment]
@blaggacao I can understand people are busy, maybe for next release. I'd rather have people fully engaged.
