### ISSUE TITLE
20.09 manual not available

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#607]
I wanted to do some QA for the release, but the manual is not available.

![Screenshot from 2020-10-06 01-23-50](https://user-images.githubusercontent.com/91113/95141916-b0465e80-0772-11eb-81ed-b15ea12419f1.png)

I was very clever and tried https://nixos.org/manual/nixos/20.09/ but it's 404. Maybe ALL manuals could made available like this...

**Comment by garbas** [comment]
That is how currently is until release is done. We might consider to open a temporary "pre" / "alpha" / "beta" channel, but this needs to be discussed with release managers first.

I'm closing this issue since all of the needed automation is in place, we (release management) just needs to decide how to rollout the release. I'll bring this up with the release managers when talking to them about #448

**Comment by acarrico** [comment]
I have the opposite issue. I went looking for manual version 20.03, but only 20.09 is available. This is bad, users should be able to easily find the correct manual for their current install, even if it is old or new. I also "guessed"  https://nixos.org/manual/nixos/20.03/, like the OP, and it isn't there. It seems like a no-brainer to have all the manuals available, and link 'stable' to the current one. On irc, ryantm suggested going to nixpkgs/doc and running nix-build, which is a helpful workaround, but this should issue should be reopened and fixed.
