### ISSUE TITLE
Download page: don't call Plasma 5 KDE

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixos-homepage#613]
**Introduce your stance**
According to @ttuegel calling this `KDE` isn't right with their branding. So it should just be `Plasma 5`.

**Comment by samueldr** [comment]
@worldofpeace can you make the edits?

If you either think you'll be lacking time, energy or aren't confident about editing the site just ask and we'll handle it :).

**Comment by worldofpeace** [comment]
> @worldofpeace can you make the edits?
> 
> If you either think you'll be lacking time, energy or aren't confident about editing the site just ask and we'll handle it :).

For sure lacking time. It's easy so I hope someone can handle it :grin: Thanks for asking

**Comment by davidak** [comment]
i think that the branding is wrong and people are more likely to know "KDE Desktop" than "Plasma", but that has to be discussed on another place. i don't care about KDE, but about usability of NixOS

i think it would be good to at least mention it like "Plasma 5 (KDE)"

**Comment by worldofpeace** [comment]
I defer to @ttuegel  because he maintains Plasma 5. It seems it's referred prominently as Plasma on the website
![Screenshot from 2020-10-09 20-01-22](https://user-images.githubusercontent.com/28888242/95640333-58f20800-0a6a-11eb-90f7-c41d35ea56a9.png)


It seems KDE would mean a group of software made by that community (and that community itself). So it's "KDE's" desktop Plasma. So it would think it would be referred to as `Plasma Desktop`

**Comment by davidak** [comment]
"Plasma Desktop" sounds good

i'm not up to date with the project

**Comment by ttuegel** [comment]
> i think that the branding is wrong and people are more likely to know "KDE Desktop" than "Plasma", but that has to be discussed on another place. i don't care about KDE, but about usability of NixOS

KDE maintainers have _specifically_ asked _us_ (in a different time and place) to stop using "KDE" to refer to the "Plasma Desktop" because they were fielding questions from confused NixOS users who went upstream looking for the "KDE" project and could only find "Plasma". Usability of NixOS is a concern, but I think "KDE Desktop" is going to cause more confusion in the long run, not less. Personally, I think they threw away a perfectly good brand, but a) it's not my (our) problem and b) it's been six years already. :shrug:

**Comment by worldofpeace** [comment]
@ttuegel I completely agree, I remember when this happened a **long** time ago. This just proves our website is finally getting the love it needs :grin:
