### ISSUE TITLE
Three different commands to install Nix?

### ISSUE THREAD

**Issue by foxit64** [NixOS/nixos-homepage#616]
**Describe the issue**

On the following pages, two different commands are described how to install Nix. Shouldn't these be the same commands?

**Page links**
- https://nixos.org/download.html#nix-quick-install

```
$ curl -L https://nixos.org/nix/install | sh
```

- https://nixos.org/guides/install-nix.html
```
sh <(curl -L https://nixos.org/nix/install) --daemon
```

Thanks

**Comment by erikarvstedt** [comment]
Just came here to report the same issue.

**Comment by garbas** [comment]
Thank you for bringing this up. We should definitely have only one way how to install it. But if you followed NixCon 2020 you might hear that not everyone agrees how we should install Nix. Since we pull `Install Nix` from https://nix.dev we ended up with two different recommendations.

I'll definitely bump the priority for this since we need to solve this quickly.

**Comment by foxit64** [comment]
One more link:

```
$ bash <(curl -L https://nixos.org/nix/install)
```

https://nixos.org/manual/nix/stable/#chap-quick-start

**Comment by foxit64** [comment]
Status?

**Comment by kubukoz** [comment]
The Manual currently shows the default method (single-user on linux, multi-user on mac) and then how you can pick a specific method, so that's fine: https://nixos.org/manual/nix/stable/installation/installing-binary.html

The other examples are unified in #774 - I updated the main page to use the multi-user install.

**Comment by fricklerhandwerk** [comment]
@foxit64 Is this satisfying enough to close the issue?
