### ISSUE TITLE
More open Matrix room settings

### ISSUE THREAD

**Issue by nesnera** [NixOS/nixos-homepage#695]
**Introduce your stance**
Matrix user

**Describe the issue**
Matrix rooms have less open settings compared to RPi. It's not very friendly for newcomers.

**Page links**
- [#nixos-aarch64](https://matrix.to/#/!ACOPNtJclKAfOLQCKK:matrix.org?via=matrix.org&via=kernelpanic.cafe&via=ruhr-uni-bochum.de)
- [Raspberry Pi](https://matrix.to/#/#raspberrypi:matrix.org?via=matrix.org&via=privacytools.io&via=tchncs.de)

Room Settings:
![image](https://user-images.githubusercontent.com/1737463/114096609-3dec3d80-98bf-11eb-8839-49fc6ce0cec4.png)
![image](https://user-images.githubusercontent.com/1737463/114096639-4b092c80-98bf-11eb-85b8-e2d25ab00190.png)

**Additional context**
I'm not sure if this difference also allows previews (= see content without registering / creating a Matrix account) 
![image](https://user-images.githubusercontent.com/1737463/114097371-3aa58180-98c0-11eb-9673-31118c45ede9.png)

**Comment by mweinelt** [comment]
I'm not quite sure who has permissions to do this, and what we as a community want.

By default operator status on IRC does not map to Admin status on Matrix, so we can't just change these settings.

And while giving backlog to anyone should be fine, since we do public logging anyway, I think having to register an account on matrix offers us some form of ratelimiting, when abuse happens.

**Comment by garbas** [comment]
I'm also not sure who has the permission for this, but it is out of scope for nixos.org website.

**Comment by nesnera** [comment]
> ..out of scope for nixos.org website.

Where would such a thing occur/resolve then?

**Comment by garbas** [comment]
This repo is about the content on the website. For infrastructure problems I would ask infra team.
