### ISSUE TITLE
Dependencies to show content

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixos-homepage#701]
I tried previewing my PR by running `nix-shell`, but gave up when it started compiling some C++ aws-sdk package.

Is there a way to reduce the set of dependencies necessary to _view content_?

**Comment by samueldr** [comment]
It is apparently by design, according to #493.

The workaround in use by some developers is to use a cachix cache which contains builds pushed by the CI/CD setup here.

**Comment by asymmetric** [comment]
Not sure if I understand. According to what @garbas said, `github:nixos/nix/latest-release` is the actual latest stable release, so it should be in cache.nixos.org?

**Comment by samueldr** [comment]
Not sure which you were ending up building, but note that there are two Nix:

https://github.com/NixOS/nixos-homepage/blob/c4a3ed90fbea5386e4060a3f3f623d52b99c9ec4/flake.nix#L10-L11

Since both manuals are produced.

I also am not sure whether this would cause a rebuild for both. My suspicions are it would since they are different inputs than what are present in Nixpkgs.
