### ISSUE TITLE
Since 2.4, the web is full of broken links to the Nix manual.

### ISSUE THREAD

**Issue by roberth** [NixOS/nixos-homepage#753]
**Introduce your stance**

Nix 2.4 split the documentation into pages. This is great in itself, but probably a decade of links from the web to here are broken by it. Do we have a solution for this?

I suppose it would be possible to have some javascript at the old location of the manual to report url fragments that couldn't be found.

This information can then be used to build a lookup table and redirect to the right page+fragment. Probably by hand, so that's why the data will be useful, to avoid useless effort.

**Describe the issue**

Especially newcomers but really anyone who reads about Nix online will encounter these broken fragments.

**Page links**

https://stackoverflow.com/questions/68588137/attributeset-expression-in-nix-expression/68588539#68588539

**Additional context**

- [ ] I already created a Pull Request

**Comment by samueldr** [comment]
> I suppose it would be possible to have some javascript at the old location of the manual to report url fragments that couldn't be found.

It could also be included (only) at the page at the end of the redirect chain, on the introduction page (`https://nixos.org/manual/nix/stable/`).

Though when I talked about this early on when talking about documentation tooling before markdown was even chosen as "the winner", and before the actual switch to authoring in Markdown on unstable, my opinion about prioritizing figuring out a solution to keep old links alive wasn't seen as a priority.

It's been a while since these discussions, so I don't recall exactly what and why, but I was a bit bummed by the lack of care about breaking existing hyperlinks.

**Comment by garbas** [comment]
While not perfect I'm not sure how this can be fixed in this repo.

**Comment by roberth** [comment]
You could restore the page and log relevant url fragments. After some time, redirect them.

**Comment by roberth** [comment]
Sadly I don't have the time and energy to overcome the lack of access to the relevant projects. Even my crash fixes take ages in that repo.

> those don't work with URL fragments

Yes, this needs to be done in javascript. It could redirect via lookup table, or when not found, make an XHR to a url that logs the fragment.
