### ISSUE TITLE
Users unable to find NixOS download

### ISSUE THREAD

**Issue by davidak** [NixOS/nixos-homepage#832]
**Introduce your stance**
While testing the new graphical installer (https://github.com/NixOS/nixpkgs/pull/161788) i gave test participants the task to "Download NixOS". I gave them the tip that the website is "nixos.org"...

I had one impatient person (Windows user, experience with Ubuntu) that just looked for "Download" and "ISO". They clicked on the download button on the frontpage and landed on the download page where they find "multi-user install", "single-user install" ... and they said "i don't know what that means...". they don't even noticed that the section is about nix and that they have to scroll down to find NixOS. i had to gave them a tip to scroll down. so they failed to find the nixos download on the nixos website

I had another person (Ubuntu user, but no linux expert) that was very cautious and read all text before deciding what to click. They found the download page and where also stuck on the nix section for several minutes. They noticed then that it's about nix and scrolled down to find NixOS.

That the GNOME ISO is "recommended" helps a lot, so people don't get stuck with the decision which download to choose!

**Describe the issue**
The issue is that there is unrelated content (related to Nix) on the NixOS website that confuses users. It has to be moved to another website only for Nix.

**Page links**
https://nixos.org/

Related to:

- https://github.com/NixOS/nixos-homepage/issues/828
- https://github.com/NixOS/nixos-homepage/issues/825

**Comment by LoveIsGrief** [comment]
This is probably comes from the lack of separation of nixOS and nix on the website. When I go to Ubuntu's home page, I don't expect to get a download link to apt, or zypper from OpenSuse's homepage. Probably there's a reason for merging nixos and nix on the same website, but it might be hurting newbies (like me) who just want nixOS when they go to the nixOS homepage.

**Comment by garbas** [comment]
This will not happen anytime soon. We've discussed this some time ago (1-2 year ago), and decided that any change regarding this would be rather negative. I would point you to the marketing team minutes on discourse, but I'm sure you know them since you were there :P

Also as much as it hurts Desktop is not a primary focus of the website. But rather DevOps experience. This does not mean there is no Desktop Linux (I'm using it), just that some users might have harder time to find the download link. That is OK, the reasons for this focus were discussed at the marketing meetings.

I don't see (at this point) any actionable thing to do with this issue and I'm closing it.

But @davidak thank you very much for doing the user testing.

**Comment by davidak** [comment]
>It's not an ISO I can put on a pendrive but rather something I can install on any Linux distribution and use instead of the package management that was shipped with it?

https://layer8.space/@RyunoKi/108279608093720330

people have to explain to them that it's also a distro. wasn't clear from website
