### ISSUE TITLE
Homepage does not explain benefits of NixOS

### ISSUE THREAD

**Issue by danbst** [NixOS/nixos-homepage#993]
The page https://nixos.org/ does not have explanation of the benefits of NixOS (not Nix, but the OS itself). 

I would like to send official promo page link, but can't find it. It was somewhere there before.

If it is there, maybe it should be added to home page?

**Comment by fricklerhandwerk** [comment]
We had this discussion multiple times recently, as you'll find in the issues in this repo related to NixOS. My impression so far is that we'd need to restructure the entire narrative to talk about Nix, Nixpkgs, and NixOS separately, but there seems to be no one with the capacity to do that kind of work at the moment. The marketing team is dormant due to lack of time.

I'd like to start with finding dedicated maintainers for Nixpkgs and NixOS documentation first, which is what we're working on with the @NixOS/documentation-team. Maybe those could take on part of the tasks required to set up at least dedicated pages on the site for each project, but really I think it should be dedicated sites.

**Comment by danbst** [comment]
yes, now I found the previous discussions.

https://discourse.nixos.org/t/landing-page-is-completely-unclear-for-new-users/22990/3
https://github.com/NixOS/nixos-homepage/issues/828
https://github.com/NixOS/nixos-homepage/issues/825
